# Generated by Django 4.1.1 on 2022-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headhunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='портфолио'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.FloatField(blank=True, null=True, verbose_name='зарплата'),
        ),
    ]
